### ISSUE TITLE
Doesn't work with eslint-loader

### ISSUE THREAD

**Issue by mqklin** [kwelch/babel-plugin-captains-log#11]
Here is a cut from my webpack config:
```
{
  test: /\.js$/,
  use: [
    'react-hot-loader',
    'cache-loader',
    {
      loader: 'babel-loader',
      options: {
        cacheDirectory: true,
        presets: [
          ['env', {targets: {browsers: ['last 2 versions']}}],
          'stage-2',
          'react',
        ],
        plugins: [
          'transform-decorators-legacy',
          'transform-react-jsx-self',
          'transform-react-jsx-source',
          'styled-components',
          'captains-log',
        ],
      },
    },
    'eslint-loader',
  ],
  exclude: /node_modules/,
},
```

If I remove `eslint-loader`, `captains-log` works as expected. 
I can create an example for reproduce the issue if necessary.

**Comment by kwelch** [comment]
Thanks, I will take a look over this coming weekend. Is there a specific error you are getting or does the plugin just no longer function?

**Comment by mqklin** [comment]
Just no longer function

**Comment by kwelch** [comment]
Good to know, thanks.

**Comment by kwelch** [comment]
Are you getting build failures? Does you build work if you remove `captains-log`?

I ask because I added `eslint-loader` to a side project that I worked on that uses `captains-log` and I had lint errors which caused the webpack build to fail. I had to scroll through the webpack output to find it though. 

Here is the repo I tested with: kwelch/family-feud-game. If this is not your issue, please attach a repo that I can reproduce. Thanks

**Comment by kwelch** [comment]
@mqklin Did the above help at all or are you still stuck in the water?

**Comment by mqklin** [comment]
@kwelch sorry for the delay.
No, I don't get build failures, `captains-log` just silent.

I'm not sure why I said the `eslint-loader` is the problem. I've tried to repeat, and now I'm 100% sure [cache-loader](https://github.com/webpack-contrib/cache-loader) causes the problem. Can you please try to run your project with it?

**Comment by kwelch** [comment]
I was able to give this a go with `cache-loader` and was still able to see my console statement with added details
![image](https://user-images.githubusercontent.com/1295580/28552311-42cb93c4-70b3-11e7-9359-002adde89beb.png)

Here is the repo I attempted with. I used my same (small) repo as before. I have pushed a new branch with the cache loader. 

https://github.com/kwelch/family-feud-game/tree/cache-loader

Can you verify with that repo, or supply I repo that I can test against?

**Comment by mqklin** [comment]
I found the bug - doesn't work with options, see [PR](https://github.com/kwelch/family-feud-game/pull/2)

**Comment by mqklin** [comment]
So I'll close the issue and open a [new one](https://github.com/kwelch/babel-plugin-captains-log/issues/12)
