### ISSUE TITLE
Need source file names

### ISSUE THREAD

**Issue by mvolkmann** [kwelch/babel-plugin-captains-log#3]
This looks like a great start! Thanks for creating this!
One more feature would convince me to use it ... pretending source file names.

**Comment by kwelch** [comment]
I completely agree. This should be pretty simple to put together. I am working on adjusting the scope string. 

Would you agree that this template would be helpful:
`{filename}({line}:{column}) - {scope}`

I think this should also have a separate flag or the scope flag should be expanded.

**Comment by mvolkmann** [comment]
I'm not sure the column is useful. I can see some people wanting the line number, but it might be good to make that optional. I'm mostly interested in the file name and function name.

**Comment by kwelch** [comment]
Currently I attempt to walk up the path, do you find that helpful? Or would it be enough to just go up to the first function.

**Comment by mvolkmann** [comment]
For me the first function is enough, but I imagine others would like more of the path.

**Comment by kwelch** [comment]
Thanks I appreciate your view. I bounced around on these ideas a few times and didn't know where to land.

**Comment by mvolkmann** [comment]
I'm really looking forward to using this!

**Comment by kwelch** [comment]
Added a PR for this. It is minimal, if you could review the tests to see how it transform that would be helpful. I will add docs later and merge.

**Comment by kwelch** [comment]
Closing with the merge of #5. 🎉
