### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by mqklin** [kwelch/babel-plugin-captains-log#6]
Just installed it and it threw `Module build failed: ReferenceError: Unknown plugin "captains-log" specified in "base" at 0, attempted to resolve relative to "/Users/mqklin/..."`
My loader (from `webpack.config.js`):

```
{
  loader: 'babel-loader',
  options: {
    presets: [
      ['env', {targets: {browsers: ['last 2 versions', 'ie >= 10']}}],
      'stage-2',
      'react',
    ],
    plugins: [
      'babel-plugin-captains-log',
      'transform-decorators-legacy',
      'transform-react-jsx-self',
      'transform-react-jsx-source',
      'styled-components',
      'transform-flow-strip-types',
    ],
  },
},
```
I can create repro if it's necessary.

**Comment by kwelch** [comment]
Thanks. This was an issue with a bad deployment. The latest published version should resolve this issue.

**Comment by mqklin** [comment]
Thank you!
