### ISSUE TITLE
Variable name injected twice

### ISSUE THREAD

**Issue by mqklin** [kwelch/babel-plugin-captains-log#7]
In my code this 
```
console.log(checked);
```
turns into this

```
console.log('checked', 'checked', checked);
```

I think it should be just

```
console.log('checked', checked);
```

isn't it? Should I create a repro?

**Comment by kwelch** [comment]
I have seen some duplication when console is called within an arrow function that is wrapped in a class. I think this is an integration bug with stage-2.

I actually just pushed a branch that repros this and duplicates 3 times.

I will attempt an idea I have one this.
